name: Build Flutter APK

on:
  push:
    branches:
      - main    # Change this if your default branch is different
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # (Optional) List the repository structure for debugging
      - name: Verify Directory Structure
        run: |
          echo "Repository root:"
          ls -la
          echo "Contents of voice-assistant-app directory:"
          ls -la voice-assistant-app

      # Install Flutter using the subosito/flutter-action
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # Specify your Flutter version here

      # Install Flutter dependencies (make sure pubspec.yaml is inside voice-assistant-app)
      - name: Install Dependencies
        run: flutter pub get
        working-directory: voice-assistant-app

      # Build the APK in release mode
      - name: Build APK
        run: flutter build apk --release
        working-directory: voice-assistant-app

      # Upload the generated APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: voice-assistant-app/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
