name: Build Flutter APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Verify Directory Structure
        run: |
          echo "Repository root:"
          ls -la
          echo "Flutter project contents:"
          ls -la voice-assistant-app/
          echo "pubspec.yaml exists:"
          test -f voice-assistant-app/pubspec.yaml && echo "Found" || echo "Missing"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Accept Android Licenses
        run: sudo flutter doctor --android-licenses

      - name: Install Dependencies
        run: flutter pub get
        working-directory: voice-assistant-app

      - name: Build APK
        run: flutter build apk --release
        working-directory: voice-assistant-app

      - name: Verify APK Exists
        run: ls -la build/app/outputs/flutter-apk/
        working-directory: voice-assistant-app

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: voice-assistant-app/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
