name: Build Flutter APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Verify directory structure before proceeding
      - name: Verify Directory Structure
        run: |
          echo "Repository root:"
          ls -la
          echo "Contents of voice-assistant-app:"
          ls -la voice-assistant-app/
          echo "Checking for pubspec.yaml..."
          if [ ! -f "voice-assistant-app/pubspec.yaml" ]; then
            echo "Error: pubspec.yaml not found! Ensure your Flutter project is correctly set up."
            exit 1
          fi

      # Setup Java (required for Android builds)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Updated Java version to avoid SDK errors

      # Install Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'

      # Check Flutter installation
      - name: Flutter Doctor
        run: flutter doctor -v

      # Accept Android SDK Licenses
      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      # Install dependencies (Flutter packages)
      - name: Install Dependencies
        run: |
          cd voice-assistant-app
          flutter pub get

      # Build the APK
      - name: Build APK
        run: |
          cd voice-assistant-app
          flutter build apk --release

      # Verify APK Exists
      - name: Verify APK Exists
        run: |
          cd voice-assistant-app
          ls -la build/app/outputs/flutter-apk/

      # Upload the APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: voice-assistant-app/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
